cloudinary:
    api-key: 712497974944343
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: ddm1dgb32
logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
pring:
    mvc:
        hiddenmethod:
            filter:
                enabled: true
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: phietee5ahGai4eDeiwoola2gahdohsa
        url: jdbc:mysql://192.168.1.208:3306/open_mind?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
